version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: version-vault-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: version-vault
    volumes:
      - mongo_data:/data/db
    networks:
      - version-vault-network

  redis:
    image: redis:7.2-alpine
    container_name: version-vault-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - version-vault-network

volumes:
  mongo_data:
  redis_data:

networks:
  version-vault-network:
    driver: bridge